[package]
name = "vectune"
version = "0.2.1"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["ClankPan <clankpan24cm@gmail.com>"]
description = "A lightweight VectorDB with Incremental Indexing, based on FreshVamana."
keywords = ["FreshVamana", "VectorDataBase", "IncrementalIndexing", "LightWeight", "DisckANN"]
categories = ["data-structures", "database", "mathematics"]
repository = "https://github.com/ClankPan/vectune"
readme = "README.md"

[dependencies]
itertools = "0.14.0"
parking_lot = {version = "0.12.5", features = []} 
rayon = "1.11.0"
rustc-hash = "2.1.1"
serde = { version = "1.0.228", features = ["derive"] }
serde_json = "1.0.145"
indicatif = { version = "0.18.3" }
dashmap = "6.1.0"
bit-vec = "0.8.0"
ic-cdk = "0.18.7"

memmap2 = "0.9.9"
anyhow = "1.0.100"
bytesize = "2.2.0"
bytemuck = "1.24.0"
bincode = "2.0.1"

log = "0.4.28"
num-format = "0.4"

# those can not be updated, as getrandom and rand next version are not compatible with wasm32-unknown-unknown yet.
getrandom = { version = "0.2.16", features = ["custom"] }
rand = { version = "0.8.5", features = ["small_rng"] }

[dev-dependencies]
rand = { version = "0.8.5", features = ["small_rng"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.113"
byteorder = "1.5.0"
indicatif = "0.18.3"
env_logger = "0.11.8"

# [features]
# wasm32-unkown-unknown = ["getrandom/custom"]
# progress-bar = ["indicatif"]
# wasm-bindgen = ["parking_lot/wasm-bindgen"]
